spring:
  profiles:
    active: dev
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - content-type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - TokenRelay
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
  security:
    oauth2:
      client:
        provider:
          devlife-keycloak-provider:
            issuer-uri: http://localhost:9091/realms/devlife
            token-uri: http://localhost:9091/realms/devlife/protocol/openid-connect/token
            authorization-uri: http://localhost:9091/realms/devlife/protocol/openid-connect/auth
            user-info-uri: http://localhost:9091/realms/devlife/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          devlife-keycloak-spring-gateway-client:
            provider: devlife-keycloak-provider
            scope: openid
            client-id: devlife
            client-secret: Cholrw3TlvIxZJz5Z5V2sH88DHjQS6zr
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: ${SERVER_HOST:8080}
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
  instance:
    prefer-ip-address: true
    hostname: api-gateway
endpoints:
  routes:
    sensitive: false


